"""Pattern definitions for AcademicLint detectors."""

# Vague terms that lack clear referents.
#
# Curated to ~30 terms that are genuinely vague in most academic contexts.
# Removed: demonstrative pronouns (this/that/these/those) which are usually
# clear when attached to a noun ("this paper", "those results"); common
# academic vocabulary (factor, issue, area, individual, element); and verbs
# that are too common to flag without context (change, relate, concern, involve).
VAGUE_TERMS = {
    # Genuinely vague nouns — almost never specific enough
    "thing",
    "things",
    "stuff",
    "society",
    "people",
    # Vague adjectives — evaluative without evidence
    "significant",
    "important",
    "interesting",
    "good",
    "bad",
    "big",
    "large",
    "great",
    # Intensifiers — add emphasis without substance
    "very",
    "really",
    "quite",
    "rather",
    "extremely",
    "incredibly",
    # Vague quantifiers — should be replaced with data
    "many",
    "some",
    "most",
    "often",
    "sometimes",
    "recently",
    # Vague verb
    "impact",
}

# Patterns indicating causal claims
CAUSAL_PATTERNS = [
    r"\b(cause[sd]?|causing)\b",
    r"\b(lead[s]?|led|leading)\s+to\b",
    r"\b(result[s]?|resulted|resulting)\s+in\b",
    r"\b(produce[sd]?|producing)\b",
    r"\b(create[sd]?|creating)\b",
    r"\b(drive[s]?|drove|driving)\b",
    r"\b(trigger[s]?|triggered|triggering)\b",
    r"\b(because\s+of|due\s+to|owing\s+to)\b",
    r"\b(as\s+a\s+result\s+of|as\s+a\s+consequence\s+of)\b",
    r"\b(bring[s]?\s+about|brought\s+about)\b",
    r"\b(give[s]?\s+rise\s+to|gave\s+rise\s+to)\b",
]

# Citation patterns (to check if claims are cited)
CITATION_PATTERNS = [
    r"\([A-Z][a-z]+,?\s+\d{4}\)",  # (Author, 2023)
    r"\([A-Z][a-z]+\s+et al\.,?\s+\d{4}\)",  # (Author et al., 2023)
    r"[A-Z][a-z]+\s+\(\d{4}\)",  # Author (2023)
    r"\[\d+(?:,\s*\d+)*\]",  # [1] or [1, 2, 3]
    r"\[[\w\s,]+\d{4}\]",  # [Author 2023]
]

# Weasel word patterns
WEASEL_PATTERNS = [
    # Vague attribution
    r"\b(some|many|most|several|various|numerous)\s+"
    r"(experts?|researchers?|scientists?|scholars?|"
    r"studies|people|critics?|observers?)\b",
    # Passive voice hedging
    r"\b(it is|it's|it has been)\s+"
    r"(believed|thought|said|known|argued|claimed|suggested|"
    r"reported|noted|observed|shown|demonstrated|proven)\b",
    # Unattributed research
    r"\b(research|studies?|evidence|data)\s+"
    r"(shows?|suggests?|indicates?|demonstrates?|proves?)\b",
    # Vague consensus
    r"\b(according to|as per)\s+(some|many|most|experts?)\b",
    r"\bit is (widely|generally|commonly)\s+"
    r"(accepted|believed|known|thought)\b",
]

# Hedge words
HEDGES = {
    "may",
    "might",
    "could",
    "possibly",
    "perhaps",
    "probably",
    "likely",
    "unlikely",
    "somewhat",
    "relatively",
    "apparently",
    "seemingly",
    "arguably",
    "tends to",
    "appears to",
    "seems to",
    "to some extent",
    "in some ways",
    "in a sense",
}

# Filler phrases
FILLER_PHRASES = [
    "in today's society",
    "in today's world",
    "throughout history",
    "since the dawn of time",
    "it is important to note that",
    "it is worth noting that",
    "it goes without saying",
    "needless to say",
    "it is clear that",
    "it is obvious that",
    "as we all know",
    "at the end of the day",
    "when all is said and done",
    "in terms of",
    "the fact that",
    "in order to",
]

# Patterns indicating need for citation
NEEDS_CITATION_PATTERNS = [
    r"\b\d+%",  # Statistics
    r"\b(studies?|research)\s+(shows?|found)\b",
    r"\b(in|during|since)\s+\d{4}\b",  # Historical dates
    r"\baccording to\b(?!\s*[\(\[])",  # Attribution without cite
    r"\b(first|largest|most|least)\b",  # Superlatives
]

# Function words (not content-bearing)
FUNCTION_WORDS = {
    "the",
    "a",
    "an",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "shall",
    "can",
    "need",
    "dare",
    "ought",
    "used",
    "to",
    "of",
    "in",
    "for",
    "on",
    "with",
    "at",
    "by",
    "from",
    "up",
    "about",
    "into",
    "over",
    "after",
    "and",
    "but",
    "or",
    "nor",
    "so",
    "yet",
    "both",
    "either",
    "neither",
    "not",
    "only",
    "own",
    "same",
    "than",
    "too",
    "very",
    "just",
    "also",
    "now",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "any",
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "as",
    "if",
    "then",
    "because",
    "while",
    "although",
    "though",
    "unless",
    "until",
    "before",
    "after",
    "above",
    "below",
    "between",
    "under",
    "again",
    "further",
    "once",
}

# Common words (top 10000) - subset for jargon detection
COMMON_WORDS = {
    "the",
    "be",
    "to",
    "of",
    "and",
    "a",
    "in",
    "that",
    "have",
    "i",
    "it",
    "for",
    "not",
    "on",
    "with",
    "he",
    "as",
    "you",
    "do",
    "at",
    "this",
    "but",
    "his",
    "by",
    "from",
    "they",
    "we",
    "say",
    "her",
    "she",
    "or",
    "an",
    "will",
    "my",
    "one",
    "all",
    "would",
    "there",
    "their",
    "what",
    "so",
    "up",
    "out",
    "if",
    "about",
    "who",
    "get",
    "which",
    "go",
    "me",
    "when",
    "make",
    "can",
    "like",
    "time",
    "no",
    "just",
    "him",
    "know",
    "take",
    "people",
    "into",
    "year",
    "your",
    "good",
    "some",
    "could",
    "them",
    "see",
    "other",
    "than",
    "then",
    "now",
    "look",
    "only",
    "come",
    "its",
    "over",
    "think",
    "also",
    "back",
    "after",
    "use",
    "two",
    "how",
    "our",
    "work",
    "first",
    "well",
    "way",
    "even",
    "new",
    "want",
    "because",
    "any",
    "these",
    "give",
    "day",
    "most",
    "us",
    "is",
    "was",
    "are",
    "were",
    "been",
    "being",
    "has",
    "had",
    "does",
    "did",
    "doing",
    "very",
    "through",
    "during",
    "before",
    "between",
    "each",
    "under",
    "again",
    "where",
    "why",
    "here",
    "should",
    "must",
    "said",
    "world",
    "still",
    "found",
    "made",
    "find",
    "long",
    "down",
    "such",
    "great",
    "those",
    "while",
    "might",
    "right",
    "thing",
    "place",
    "around",
    "since",
    "much",
    "many",
    "every",
    "never",
    "last",
    "using",
    "however",
    "always",
    "without",
    "within",
    "part",
    "although",
    "against",
    "often",
    "really",
    "something",
    "nothing",
    "another",
    "study",
    "different",
    "research",
    "information",
    "important",
    "example",
    "system",
    "number",
    "point",
    "result",
    "following",
}
